package com.hi.dear.ui

object FirebaseConstants {
    val giftField="gift"
    const val gifTable = "gift"
    const val notification_type = "notificationType"
    const val time_field = "time"
    const val last_message_table_name = "msg"
    const val msg = "msg"
    const val sender_id = "senderId"
    const val receiver_id = "receiverId"
    const val chat_id = "id"
    const val chat_table_post_fix = "chat"
    const val statusField = "status"
    const val sentRequestTable_post_fix = "RS"
    const val requestReceivedTable_post_fix = "RR"
    const val pictureField = "pic"
    const val userInfoTable = "userInfo"
    const val authInfoTable = "authInfo"
    const val notificationTable = "notifications"
    const val coinTable = "coin"
    const val ageField = "age"
    const val userNameField = "userName"
    const val genderField = "gender"
    const val endTimeField = "startTime"
    const val countryField = "country"
    const val cityField = "city"
    const val emailOrMobileField = "emailOrMobile"
    const val passwordField = "password"
    const val userIdField = "userId"
    const val aboutField = "about"
    const val coinField = "coin"
    const val boostedTable = "boostedProfile"
}